# permissions for end users to view secretscopycustomresources.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: secrets-syncronization-operator
    app.kubernetes.io/managed-by: kustomize
  name: secretscopycustomresource-viewer-role
rules:
- apiGroups:
  - apps.example.com
  resources:
  - secretscopycustomresources
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps.example.com
  resources:
  - secretscopycustomresources/status
  verbs:
  - get
