# permissions for end users to edit secretscopycustomresources.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: secrets-syncronization-operator
    app.kubernetes.io/managed-by: kustomize
  name: secretscopycustomresource-editor-role
rules:
- apiGroups:
  - apps.example.com
  resources:
  - secretscopycustomresources
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.example.com
  resources:
  - secretscopycustomresources/status
  verbs:
  - get
