apiVersion: apps.example.com/v1
kind: SecretsCopyCustomResource
metadata:
  labels:
    app.kubernetes.io/name: secrets-syncronization-operator
    app.kubernetes.io/managed-by: kustomize
  name: secretscopycustomresource-sample
  namespace: space1
spec:
  destinationSecrets:
  - secret1
  - secret2
  sourceNamespace: default
